#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Start new post (opening in Vim)
"""

from __future__ import print_function
import os
from slugify import slugify
from datetime import datetime


TEMPLATE = """Title: {title}
Date: {date}
Author: Elias Dorneles
Slug: {title_slug}

Write here...
"""

POSTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'site', 'blog')


def run(args):
    try:
        title = raw_input('Title (hit ^C to cancel): ')
    except KeyboardInterrupt:
        return

    if not title:
        print('No title given, giving up')
        return

    slug = slugify(title)
    date = datetime.now().strftime('%Y-%m-%d %H:%M')

    snippet = TEMPLATE.format(title=title, title_slug=slug, date=date)

    filename = os.path.join(POSTS_DIR, '%s.md' % slug)

    with open(filename, 'w') as f:
        f.write(snippet)

    print('Opening file: %s' % filename)
    os.execvp('vim', ['vim', '+6', filename])

if '__main__' == __name__:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)

    args = parser.parse_args()
    run(args)
